modLoader="javafml"
loaderVersion="[28,)"
logoFile="logo.png"
# todo: before first public release need change it url.
issueTrackerURL="https://github.com/MairwunNx/ProjectEssentials/issues"

[[mods]]
    modId="project_essentials"
    version="1.14.4-0.3.0"
    displayName="Project Essentials"
    credits="Thanks JetBrains for Intellij IDEA license!"
    authors="MairwunNx (Pavel Erokhin)"
    # todo: before first public release need change it url.
    updateJSONURL="https://raw.githubusercontent.com/MairwunNx/ProjectEssentials/MC-1.14.4/update.json"
    displayURL="https://github.com/MairwunNx/ProjectEssentials"
    description='''
    Project Essentials - minecraft command mod - adds commands for use in-game.
    '''

[[dependencies.mod]]
    modId="project_essentials_core"
    mandatory=true
    versionRange="[1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.projectessentials]]
    modId="project_essentials_permissions"
    mandatory=true
    versionRange="[0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.projectessentials]]
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.projectessentials]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"
