modLoader="javafml"
loaderVersion="[28,)"
issueTrackerURL="https://github.com/ProjectEssentials/ProjectEssentials/issues"

[[mods]]
    modId="project_essentials_basic"
    version="${file.jarVersion}"
    displayName="Project Essentials Basic"
    credits="hujle, JetBrains, all forge developers, and other contributors"
    authors="MairwunNx (Pavel Erokhin)"
    updateJSONURL="https://raw.githubusercontent.com/ProjectEssentials/ProjectEssentials/MC-1.14.4/updatev2.json"
    displayURL="https://github.com/MairwunNx/ProjectEssentials"
    description='''
    A basic module of Project Essentials. This module adds a few basic commands
    in minecraft for the project. Many of the commands in this module will be
    familiar to you from EssentialsX.
    '''

[[dependencies.project_essentials_basic]]
    modId="project_essentials_core"
    mandatory=true
    versionRange="[2,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.project_essentials_basic]]
    modId="forge"
    mandatory=true
    versionRange="[28,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.project_essentials_basic]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.14.4]"
    ordering="NONE"
    side="BOTH"
